version: "3.9"
services:
  tooling_frontend:
    build: .
    image: johnstx/tooling
    ports:
      - "5000:80"
    volumes:
      - tooling_frontend:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "toolingdb"
      MYSQL_USER: "staxx"
      MYSQL_PASSWORD: "movement"
      MYSQL_ROOT_PASSWORD: "password1"
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db:
