   pipeline {

        environment {
        registry = "johnstx/tooling" 
        registryCredential = 'dockerhub-login' // Jenkins credentials ID for Docker Hub
        BUILD_TAG = 'feature-0.0.1'
        }
        
        agent any

        stages {

          stage ('Checkout SCM') {
            steps {
              git branch: 'feature' , url : 'https://github.com/Johnstx/Tooling-Docker-.git',   credentialsId: 'github-login'
            }
          }

          // stage('Docker Build Image') {
          //      steps {
          //             script {
          //                 // Build the Docker image and assign it to dockerImage
          //                 dockerImage = docker.build("${registry}:latest")
          //                   }
          //             }
          //     }
          // }



          stage('Docker Build image') {
            steps {
                script {
                    //  docker.withRegistry( '' ,  'dockerhub-login' ) {
                          // Build the Docker image and assign it to dockerImage 
                          dockerImage = docker.build("${env.REGISTRY}:${env.BUILD_TAG}")
                           }
                }
            }

  //         // stage ('tag the docker image') {
  //         //   steps {
  //         //       sh 'docker image tag ${registry}:latest ${registry}:feature-0.0.1'
  //         //       }
  //         // }

          stage('Deploy docker image to docker hub') {
            steps {
              script {
                         // log in to docker hub
                      docker.withRegistry ( '', registryCredential) {
                            dockerImage.push()
                 }
              }

            }
          }
      

          stage('Remove unsused images'){
             steps{
                    sh "docker rmi $registry:latest"
                    sh "docker rmi ${registry}:feature-0.0.1"
          }
        }

      }

        }


  
